### ISSUE TITLE
How to inference

### ISSUE THREAD

**Issue by xcaizewu** [gasharper/PyramidFlow#4]
Thank you for opening the source code. Can you provide the code of model inference? My email is caizewu1994@163.com

**Comment by gasharper** [comment]
The inference process is the same as the evaluation process. 
You can refer to the following code in trian.py: 
https://github.com/gasharper/PyramidFlow/blob/c463b1cb0c2b084cdbae290234e3f8657298e981/train.py#L59-L80

**Comment by pribadihcr** [comment]
I think we need the inference demo, start from how to load the trained model and infer the test image.
