### ISSUE TITLE
您好，train过程遇到的问题

### ISSUE THREAD

**Issue by caihaocong** [gasharper/PyramidFlow#8]
您好，在train过程中，加载数据集遇到 “AttributeError: Can't pickle local object 'fix_randseed.<locals>.seed_worker'” 的问题，请问您有遇到过吗？

**Comment by gasharper** [comment]
我是在linux下训练的，pytorch需要版本>=1.9
可能是windows下多进程跟linux下不一样的缘故。
看看设置num_workers=0是否有用？
